# Generated by Django 4.1.6 on 2023-03-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_movie_image_link_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.IntegerField(default=2000),
        ),
    ]
