# Generated by Django 4.1.6 on 2023-03-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='liked_posts',
            field=models.ManyToManyField(to='main.discussionpost'),
        ),
    ]
