# Generated by Django 4.1.6 on 2023-02-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
