# Generated by Django 4.1.7 on 2023-03-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionpost',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_likes',
            field=models.IntegerField(default=0),
        ),
    ]
