# Generated by Django 4.1.6 on 2023-03-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_myuser_liked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
