# Generated by Django 4.1.7 on 2023-03-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_discussionpost_post_likes_movie_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
