# Generated by Django 4.1.6 on 2023-03-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_length_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
