# Generated by Django 4.1.6 on 2023-03-21 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movielist_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_likes',
            new_name='watched',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='liked_posts',
        ),
        migrations.CreateModel(
            name='Movie_Watched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discussionpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
