# Generated by Django 4.1.6 on 2023-03-22 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_movie_likes_movie_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_watched',
            name='date_watched',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
