# Generated by Django 4.1.6 on 2023-03-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_movie_watched_date_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
