# Generated by Django 4.1.6 on 2023-03-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_myuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion_likes',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie_watched',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
